### ISSUE TITLE
RNAseq libraryType and RELACS dedup

### ISSUE THREAD

**Issue by katsikora** [maxplanck-ie/BigRedButton#1]
- I think the check for RNAseq library type <code> libraryType.startswith("NEBNext Low Input RNA Library"): </code> is not working properly, as <code>CMD.extend(['--libraryType', '0'])</code> doesn't appear to take place. In Parkour, this information is stored in the "Protocol" field. Maybe another field should be checked?
- For RELAX, the DNA mapping pipeline should rather be run with <code>--UMIDedup</code> instead of <code>--dedup</code>. Maybe a check is needed first if UMIs are present, although this should be state of the art.

**Comment by dpryan79** [comment]
It's likely that they're just using a different kit now for low input RNA-seq, since that at least used to work.

UMIs are now always present in RELACS data (they weren't originally). We should just update the command to assume that.

**Comment by katsikora** [comment]
@LeilyR had a visitor today who had unstranded data,  with NEBNext, if I understood correctly?
In his case, the Button ran with the default libraryType 2.

**Comment by dpryan79** [comment]
Ah, if you find out the project number we can have a look tomorrow. It has to be labeled correctly in parkour, since I had hard coded that setting.

**Comment by katsikora** [comment]
I've added <code>--UMIDedup<code> to RELACS.

**Comment by katsikora** [comment]
Both fixes are now in place. RNAseq fix is tested and confirmed.

I see I've committed the changes as Devon ;)

**Comment by dpryan79** [comment]
lol
